// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr85zPsu7ysaXw_YCEYeO34mzkm9uMrJc',
    appId: '1:602859222671:android:fc09c36ac5c06a22c8e2fa',
    messagingSenderId: '602859222671',
    projectId: 'tuticket-f3f6b',
    databaseURL: 'https://tuticket-f3f6b-default-rtdb.firebaseio.com',
    storageBucket: 'tuticket-f3f6b.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXxj8cGVpR7Vy4O5Di8p1tp_5Nh8bgbHM',
    appId: '1:602859222671:web:8f53a4cac3a54242c8e2fa',
    messagingSenderId: '602859222671',
    projectId: 'tuticket-f3f6b',
    authDomain: 'tuticket-f3f6b.firebaseapp.com',
    databaseURL: 'https://tuticket-f3f6b-default-rtdb.firebaseio.com',
    storageBucket: 'tuticket-f3f6b.appspot.com',
    measurementId: 'G-MGWW4NT52E',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXxj8cGVpR7Vy4O5Di8p1tp_5Nh8bgbHM',
    appId: '1:602859222671:web:aba724e0432c485fc8e2fa',
    messagingSenderId: '602859222671',
    projectId: 'tuticket-f3f6b',
    authDomain: 'tuticket-f3f6b.firebaseapp.com',
    databaseURL: 'https://tuticket-f3f6b-default-rtdb.firebaseio.com',
    storageBucket: 'tuticket-f3f6b.appspot.com',
    measurementId: 'G-190S873E5T',
  );

}