name: Flutter

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    # Update Node.js to version 20.x
    - name: Use Node.js 20.x
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'
    # The flutter action needs java so include it
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    # Include the flutter action
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    # Get flutter packages
    - run: flutter pub get





      
