name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: suborbital/flutter@v1  # Use the suborbital/flutter action

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source (Flutter specific)
        run: flutter analyze


      
